name: "Reporte de Bug"
description: "Reporta un bug para ayudarnos a mejorar"
title: "[BUG] Título del bug"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Descripción del Bug
        Una descripción clara y concisa del bug.

  - type: input
    id: steps_to_reproduce
    attributes:
      label: "Pasos para Reproducir"
      description: "Describe los pasos necesarios para reproducir el bug."
      placeholder: "1. Ir a '...'\n2. Hacer clic en '...'\n3. Desplazarse hacia '...'\n4. Ver el error"

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Comportamiento Esperado"
      description: "Describe lo que esperabas que sucediera."
      placeholder: "Una descripción clara y concisa de lo que esperabas que sucediera."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Comportamiento Observado"
      description: "Describe lo que realmente sucedió."
      placeholder: "Una descripción clara y concisa de lo que realmente sucedió."

  - type: textarea
    id: additional_info
    attributes:
      label: "Información Adicional"
      description: "Cualquier otra información que consideres relevante."
